### ISSUE TITLE
OpenMP parallel slower than serial

### ISSUE THREAD

**Issue by kidharb** [tgmattso/OpenMP_Common_Core#1]
Hi Tim, 

Sorry for contacting you this way but I am really struggling with openmp after going through your course on YouTube.
I have profiled the parallel and serial version of the following code and came up with the following results :

Program was compiled and run like this (source code here https://github.com/kidharb/openmp/blob/master/matmul.c)

I am not doing any data work in the for loops to rule out false sharing.
System is mid 2012 Macbook Pro, Core i7 2.6Ghz, MacOS 10.13.6, 8Gb Ram, gcc version 8.3.0.

Can you help me understand what I am doing wrong so as to get the results below?

>gcc -fopenmp matmul.c ; ./a.out 100                                                                                                                                   

N = 10
Serial took 0.400001 usec
Parallel took 42.020000 usec

N = 100
Serial took 42.660000 usec
Parallel took 70.090000 usec

N = 1000
Serial took 4230.839998 usec
Parallel took 3043.949998 usec

OpenMP Env

OPENMP DISPLAY ENVIRONMENT BEGIN
  _OPENMP = '201511'
  OMP_DYNAMIC = 'FALSE'
  OMP_NESTED = 'FALSE'
  OMP_NUM_THREADS = '8'
  OMP_SCHEDULE = 'DYNAMIC'
  OMP_PROC_BIND = 'FALSE'
  OMP_PLACES = ''
  OMP_STACKSIZE = '2097152'
  OMP_WAIT_POLICY = 'PASSIVE'
  OMP_THREAD_LIMIT = '4294967295'
  OMP_MAX_ACTIVE_LEVELS = '2147483647'
  OMP_CANCELLATION = 'FALSE'
  OMP_DEFAULT_DEVICE = '0'
  OMP_MAX_TASK_PRIORITY = '0'
OPENMP DISPLAY ENVIRONMENT END

**Comment by tgmattso** [comment]
Your problem has nothing to do with OpenMP or false sharing.  The problem is you are solving a problem with compute that scales as N squared with memory traffic that scales as N squared.  You will see some improvement for large problems with multiple threads if the cores are spread out to different memory controlers on chip, but you'll never see much improvement since you are memory bound.  I don't cover it in my tutorial though I do in my lectures.  You can never get around Amdahl's law and you can never get around making memory bound problems run faster by throwing threads at them.
